# Configuration for Together_AI
# Generated dynamically from CSV data
# Tier: community | Models: llama-2-70b|llama-2-13b|mistral-7b

provider:
  name: "Together_AI"
  tier: "community"
  base_url: "https://api.together.xyz/v1"
  api_key: "xxx"

models:
  source: "llama-2-70b|llama-2-13b|mistral-7b"
  dynamic_loading: false
  available_models:
    - "llama-2-70b"
    - "llama-2-13b"
    - "mistral-7b"
  
configuration:
  timeout: "30s"
  max_retries: 3
  
rate_limiting:
  enabled: true
  requests_per_minute: 60
  
capabilities:
  - chat

metadata:
  description: "Open source models with competitive pricing"
  auto_generated: true
  csv_source: "providers.csv"
  generated_at: "2025-08-22 20:45:00"
  
# Tier-specific configurations
community_features:
  free_tier: true
  rate_limited: true
  best_effort: true
  open_source: true